[instructor]
username = "purplecandle"
password = "purplecandle"

MONGO_URI = "mongodb+srv://kbanner_db_user:8hbb5Sn9OL9wemAW@exam-databank.x4f5mei.mongodb.net/?retryWrites=true&w=majority&appName=exam-databank"
